name: CICD Pipeline


on:
  push:
    branches:
      - main


jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  security-check:
    runs-on: ubuntu-latest
    needs: compile

    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@v0.2.1
        with:
          scan-type: fs
          format: table
          output: trivy-report.txt

      - name: Run Gitleaks Code Scan
        uses: zricethezav/gitleaks-action@v1.0.12
        with:
          config: gitleaks.toml


      

      

     



      

      
      
      

      

      

