name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/'
    branches:
      - main

jobs:
  build-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      


name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/'
    branches:
      - main
  workflow_run:
    workflows: ["Backend CI/CD"]
    types:
      - completed

jobs:
  build-deploy-frontend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      

      

     



      

      
      
      

      

      

